#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceMaker
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="invoiceprocess")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertinvoiceline(invoiceline instance);
    partial void Updateinvoiceline(invoiceline instance);
    partial void Deleteinvoiceline(invoiceline instance);
    partial void Insertreference(reference instance);
    partial void Updatereference(reference instance);
    partial void Deletereference(reference instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::InvoiceMaker.Properties.Settings.Default.invoiceprocessConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<invoiceline> invoicelines
		{
			get
			{
				return this.GetTable<invoiceline>();
			}
		}
		
		public System.Data.Linq.Table<reference> references
		{
			get
			{
				return this.GetTable<reference>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.invoicelines")]
	public partial class invoiceline : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _invoiceID;
		
		private string _firstname;
		
		private string _lastname;
		
		private string _ref_number;
		
		private System.Nullable<decimal> _hoursthisperiod;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OninvoiceIDChanging(int value);
    partial void OninvoiceIDChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void Onref_numberChanging(string value);
    partial void Onref_numberChanged();
    partial void OnhoursthisperiodChanging(System.Nullable<decimal> value);
    partial void OnhoursthisperiodChanged();
    #endregion
		
		public invoiceline()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoiceID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int invoiceID
		{
			get
			{
				return this._invoiceID;
			}
			set
			{
				if ((this._invoiceID != value))
				{
					this.OninvoiceIDChanging(value);
					this.SendPropertyChanging();
					this._invoiceID = value;
					this.SendPropertyChanged("invoiceID");
					this.OninvoiceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="VarChar(50)")]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this.OnfirstnameChanging(value);
					this.SendPropertyChanging();
					this._firstname = value;
					this.SendPropertyChanged("firstname");
					this.OnfirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="VarChar(50)")]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this.OnlastnameChanging(value);
					this.SendPropertyChanging();
					this._lastname = value;
					this.SendPropertyChanged("lastname");
					this.OnlastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ref_number", DbType="VarChar(50)")]
		public string ref_number
		{
			get
			{
				return this._ref_number;
			}
			set
			{
				if ((this._ref_number != value))
				{
					this.Onref_numberChanging(value);
					this.SendPropertyChanging();
					this._ref_number = value;
					this.SendPropertyChanged("ref_number");
					this.Onref_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoursthisperiod", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> hoursthisperiod
		{
			get
			{
				return this._hoursthisperiod;
			}
			set
			{
				if ((this._hoursthisperiod != value))
				{
					this.OnhoursthisperiodChanging(value);
					this.SendPropertyChanging();
					this._hoursthisperiod = value;
					this.SendPropertyChanged("hoursthisperiod");
					this.OnhoursthisperiodChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reference")]
	public partial class reference : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _referenceID;
		
		private string _firstname;
		
		private string _lastname;
		
		private string _ref_number;
		
		private System.Nullable<short> _customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnreferenceIDChanging(int value);
    partial void OnreferenceIDChanged();
    partial void OnfirstnameChanging(string value);
    partial void OnfirstnameChanged();
    partial void OnlastnameChanging(string value);
    partial void OnlastnameChanged();
    partial void Onref_numberChanging(string value);
    partial void Onref_numberChanged();
    partial void OncustomerChanging(System.Nullable<short> value);
    partial void OncustomerChanged();
    #endregion
		
		public reference()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenceID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int referenceID
		{
			get
			{
				return this._referenceID;
			}
			set
			{
				if ((this._referenceID != value))
				{
					this.OnreferenceIDChanging(value);
					this.SendPropertyChanging();
					this._referenceID = value;
					this.SendPropertyChanged("referenceID");
					this.OnreferenceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				if ((this._firstname != value))
				{
					this.OnfirstnameChanging(value);
					this.SendPropertyChanging();
					this._firstname = value;
					this.SendPropertyChanged("firstname");
					this.OnfirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastname", DbType="VarChar(50)")]
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				if ((this._lastname != value))
				{
					this.OnlastnameChanging(value);
					this.SendPropertyChanging();
					this._lastname = value;
					this.SendPropertyChanged("lastname");
					this.OnlastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ref_number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ref_number
		{
			get
			{
				return this._ref_number;
			}
			set
			{
				if ((this._ref_number != value))
				{
					this.Onref_numberChanging(value);
					this.SendPropertyChanging();
					this._ref_number = value;
					this.SendPropertyChanged("ref_number");
					this.Onref_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer", DbType="SmallInt")]
		public System.Nullable<short> customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				if ((this._customer != value))
				{
					this.OncustomerChanging(value);
					this.SendPropertyChanging();
					this._customer = value;
					this.SendPropertyChanged("customer");
					this.OncustomerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
