<?xml version="1.0" encoding="utf-8"?><Database Name="invoiceprocess" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.15;Initial Catalog=invoiceprocess;Persist Security Info=True;User ID=invoicemaster" SettingsObjectName="InvoiceMaker.Properties.Settings" SettingsPropertyName="invoiceprocessConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.invoicelines" Member="invoicelines">
    <Type Name="invoiceline">
      <Column Name="invoiceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ref_number" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="hoursthisperiod" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.reference" Member="references">
    <Type Name="reference">
      <Column Name="referenceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ref_number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="customer" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
</Database>